### ISSUE TITLE
Could not open settings generic class cache

### ISSUE THREAD

**Issue by Justman100** [easystartup-io/suggest-feature#5]
Get [this](https://scans.gradle.com/s/luf2qqc5sspvo) if I want build the Backend!

**Comment by easystartup-io** [comment]
@Justman100  which java version are you using and which gradle ? Please check https://github.com/easystartup-io/suggest-feature/blob/main/backend/Dockerfile for the gradle and java version

**Comment by easystartup-io** [comment]
@Justman100  Would love it if you could update the documentation for making it easier for others to build. https://github.com/easystartup-io/suggest-feature/blob/main/gitbook-docs/self-host/build-and-deploy.md

**Comment by Justman100** [comment]
@easystartup-io

Caused by: com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'Command createIndexes requires authentication' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "Command createIndexes requires authentication", "code": 13, "codeName": "Unauthorized"}

**Comment by Justman100** [comment]
@easystartup-io

> Caused by: com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'Command createIndexes requires authentication' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "Command createIndexes requires authentication", "code": 13, "codeName": "Unauthorized"}

**Comment by easystartup-io** [comment]
@Justman100 Which version of mongo are you using ? Also if your mongo needs authentication you need to specify it

**Comment by easystartup-io** [comment]
@Justman100 You can set the env variable 
MONGO_URL based on your mongo url auth and pass

it’s default value is mongodb://localhost:27017

**Comment by easystartup-io** [comment]
mongodb://user:pasd@192.168.1.39?authSource=admin

**Comment by Justman100** [comment]
> @Justman100 Which version of mongo are you using ? Also if your mongo needs authentication you need to specify it

8.0.0-rc20

**Comment by Justman100** [comment]
> mongodb://user:pasd@192.168.1.39?authSource=admin

I did! But only the same error appears

**Comment by Justman100** [comment]
Now comes this:

> io.kubernetes.client.openapi.ApiException: Message: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8080

**Comment by easystartup-io** [comment]
@Justman100 Sorry for replying late, was on a trek in the alps. Kubernetes exception can be ignored. Kubernetes exception should not be relevant. That runs in a different thread and should not effect the main workflow. Are you facing any other issues ? I have not yet tested in mongo 8.0.0 since it is still in release candidiate. Could you try mongo 7. Please email open@suggestfeature.com And we can setup a sync call if you are still facing issues.

**Comment by Justman100** [comment]
> @Justman100 Sorry for replying late, was on a trek in the alps. Kubernetes exception can be ignored. Kubernetes exception should not be relevant. That runs in a different thread and should not effect the main workflow. Are you facing any other issues ? I have not yet tested in mongo 8.0.0 since it is still in release candidiate. Could you try mongo 7. Please email [open@suggestfeature.com](mailto:open@suggestfeature.com) And we can setup a sync call if you are still facing issues.

The full error message:

> io.kubernetes.client.openapi.ApiException: Message: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8080
HTTP response code: 0
HTTP response body: null
HTTP response headers: null
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:1032) ~[client-java-api-20.0.1.jar!/:na]
        at io.kubernetes.client.openapi.apis.NetworkingV1Api.listNamespacedIngressWithHttpInfo(NetworkingV1Api.java:3541) ~[client-java-api-20.0.1.jar!/:na]
        at io.kubernetes.client.openapi.apis.NetworkingV1Api.access$4900(NetworkingV1Api.java:47) ~[client-java-api-20.0.1.jar!/:na]
        at io.kubernetes.client.openapi.apis.NetworkingV1Api$APIlistNamespacedIngressRequest.execute(NetworkingV1Api.java:3708) ~[client-java-api-20.0.1.jar!/:na]
        at io.easystartup.suggestfeature.services.IngressUpdateService.listAndPatchIngresses(IngressUpdateService.java:79) ~[!/:1.0]
        at io.easystartup.suggestfeature.services.IngressUpdateService.syncIngressAndVerifiedCustomHostnameDomains(IngressUpdateService.java:63) ~[!/:1.0]
        at io.easystartup.suggestfeature.services.IngressUpdateService.lambda$new$0(IngressUpdateService.java:52) ~[!/:1.0]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8080
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.12.0.jar!/:na]
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:1028) ~[client-java-api-20.0.1.jar!/:na]
        ... 7 common frames omitted
        Suppressed: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
                ... 24 common frames omitted
        Caused by: java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnect(Native Method)
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
                at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
                at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
                at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
                at java.base/java.net.Socket.connect(Socket.java:751)
                at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
                at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
                ... 23 common frames omitted
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[na:na]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:751) ~[na:na]
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295) ~[okhttp-4.12.0.jar!/:na]
        ... 23 common frames omitte

**Comment by easystartup-io** [comment]
@Justman100 the above kubernetes messages are irrelevant. Nevertheless I have pushed an update which will ensure above log messages are not printed. You can pull the latest changes. To run the whole suite, please read the guide present at https://docs.suggestfeature.com/suggest-feature/self-host/build-and-deploy . You could also message at open@suggestfeature.com and we could check it over a call convenient to you.

**Comment by Justman100** [comment]
> @Justman100 the above kubernetes messages are irrelevant. Nevertheless I have pushed an update which will ensure above log messages are not printed. You can pull the latest changes. To run the whole suite, please read the guide present at https://docs.suggestfeature.com/suggest-feature/self-host/build-and-deploy . You could also message at [open@suggestfeature.com](mailto:open@suggestfeature.com) and we could check it over a call convenient to you.

Okay, I think that's working now! I'll probably update the docs! But what is the default admin user? Or how do I create one?

**Comment by Justman100** [comment]
@easystartup-io

Okay! Got it! Although... now comes this:

> com.amazonaws.services.simpleemail.model.AmazonSimpleEmailServiceException: The security token included in the request is invalid. (Service: AmazonSimpleEmailService; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 056b88da-843d-455d-a262-bec8a22e0961; Proxy: null)
